package cn.lovingliu.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private Long id;

    private String phone;

    private String username;

    private String password;

    private String question;

    private String answer;

    private Integer role;

    private String portrait;

    private Integer ststus;

    private Date createdTime;

    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_park_user
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.id
     *
     * @return the value of school_park_user.id
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.id
     *
     * @param id the value for school_park_user.id
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.phone
     *
     * @return the value of school_park_user.phone
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.phone
     *
     * @param phone the value for school_park_user.phone
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.username
     *
     * @return the value of school_park_user.username
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.username
     *
     * @param username the value for school_park_user.username
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.password
     *
     * @return the value of school_park_user.password
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.password
     *
     * @param password the value for school_park_user.password
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.question
     *
     * @return the value of school_park_user.question
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.question
     *
     * @param question the value for school_park_user.question
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.answer
     *
     * @return the value of school_park_user.answer
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.answer
     *
     * @param answer the value for school_park_user.answer
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.role
     *
     * @return the value of school_park_user.role
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.role
     *
     * @param role the value for school_park_user.role
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.portrait
     *
     * @return the value of school_park_user.portrait
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.portrait
     *
     * @param portrait the value for school_park_user.portrait
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.ststus
     *
     * @return the value of school_park_user.ststus
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public Integer getStstus() {
        return ststus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.ststus
     *
     * @param ststus the value for school_park_user.ststus
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setStstus(Integer ststus) {
        this.ststus = ststus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.created_time
     *
     * @return the value of school_park_user.created_time
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.created_time
     *
     * @param createdTime the value for school_park_user.created_time
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_park_user.updated_time
     *
     * @return the value of school_park_user.updated_time
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_park_user.updated_time
     *
     * @param updatedTime the value for school_park_user.updated_time
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_user
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", question=").append(question);
        sb.append(", answer=").append(answer);
        sb.append(", role=").append(role);
        sb.append(", portrait=").append(portrait);
        sb.append(", ststus=").append(ststus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}