package cn.lovingliu.mapper;

import cn.lovingliu.pojo.Pictures;

import java.util.List;

public interface PicturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int insert(Pictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int insertSelective(Pictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    Pictures selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int updateByPrimaryKeySelective(Pictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_pictures
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int updateByPrimaryKey(Pictures record);

    int batchInsert(List<Pictures> picturesList);
}