package cn.lovingliu.mapper;

import cn.lovingliu.pojo.Record;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_park_record
     *
     * @mbg.generated Fri Feb 07 18:15:37 CST 2020
     */
    int updateByPrimaryKey(Record record);
}